<?php 
    $data['title'] = "MAKDFS: Privacy policy";
    $data['desc'] = "Best crypto curency trading platform.";
    $data['keyword'] = "";
    $data['imgurl'] = base_url()."assets/images/blog/blog-post-small-3.jpg";
    $data['url'] = base_url();

    $this->load->view('components/header',$data);
?>

<div style="height:150px"></div>
        <section class="terms-of-services">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<h2>Privacy Policy</h2>
						<hr><br>

<h3>What Personal Data does MAKDFS collect and process?</h3>
<p>Personal data is data that identifies an individual or relates to an identifiable individual. This includes data you provide to us, data which is collected about you automatically, and data we obtain from third parties.</p>
<p>Information you provide to us. To open an account and access our services, we'll ask you to provide us with some data about yourself. This data is either required by law (e.g., to verify your identity and comply with “Know Your Customer” obligations), necessary to provide the requested services (e.g., you will need to provide your email address in order to open your account), or is relevant for certain specified purposes, described in greater detail below. In some cases, if we add services and features you may be asked to provide us with additional data.</p>
<p>Failure in providing the data required implies that MAKDFS will not be able to offer you our services.</p>
<h4>We may collect the following types of information from you:</h4>
<table>
    <thead>
        <tr>
            <th style="width: 250px;">Category of Personal Data</th>
            <th>Types of Personal Data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Personal Identification Data.</td>
            <td>Full name, e-mail address, gender, home address, phone address, phone number, date of birth, nationality, signature, utility bills, photographs, and a video recording of you</td>
        </tr>
        <tr>
            <td>Sensitive and Biometric Personal Data</td>
            <td>MAKDFS may also collect sensitive personal data when permitted by local law or with your consent, such as biometric information, for example to verify your identity by comparing the facial scan data extracted from your selfie or video with the photo in your government issued identity document</td>
        </tr>
        <tr>
            <td>Government Identifiers</td>
            <td>Government issued identity documents such as passport, national identification number, national identity card details, drivers license numbers</td>
        </tr>
        <tr>
            <td>Institutional Information</td>
            <td>Proof of legal formation, personal identification data for all material beneficial owners, personal data about the board of directors senior persons responsible for the operations of the body corporate</td>
        </tr>
        <tr>
            <td>Financial Information</td>
            <td>Bank account information, payment card information, source of funding, source of wealth,</td>
        </tr>
        <tr>
            <td>Transaction Information</td>
            <td>Information about the transaction you make on our services, such as the name of the recipient, your name and e-mail</td>
        </tr>
        <tr>
            <td>Contact Information</td>
            <td>E-mail address, country, region,</td>
        </tr>
    </tbody>
</table>
<p>Information we collect from you automatically. To the extent permitted under the applicable law, we may collect certain types of information automatically, for example whenever you interact with us or use the services. This information helps us address customer support issues, improve the performance of our sites and services, maintain and or improve your user experience, and protect your account from fraud by detecting unauthorized access.</p>





						<h3>User Anonymity</h3>
						<p>User Anonymity: Provide options for anonymous user accounts that do not require personally identifiable information. This can be achieved by using pseudonyms or cryptographic identifiers.</p>
						<h3>Secure Data Storage</h3>
						<p>Secure Data Storage: Implement strong encryption techniques to safeguard user data, including personal details, transaction history, and wallet information. Consider adopting decentralized storage solutions to minimize the risk of data breaches.</p>
						<h3>Two-Factor Authentication (2FA)</h3>
                        <p>Two-Factor Authentication (2FA): Encourage users to enable 2FA for their accounts, adding an extra layer of security. This typically involves a combination of passwords and temporary authentication codes generated by an app or sent via SMS.</p>
                        <h3>Privacy-Focused Cryptocurrencies</h3>
                        <p>Privacy-Focused Cryptocurrencies: Consider integrating privacy-oriented cryptocurrencies like Monero, Zcash, or Dash into your platform. These cryptocurrencies utilize advanced cryptographic techniques to obfuscate transaction details, providing enhanced privacy for users.</p>
                        <h3>Transparent Privacy Policy</h3>
                        <p>Transparent Privacy Policy: Develop a comprehensive privacy policy that clearly outlines how user data is collected, used, and protected. Make it easily accessible on your website and ensure that users have the ability to opt out of data sharing or third-party disclosures.</p>
                        <h3>Minimal Data Collection</h3>
                        <p>Minimal Data Collection: Collect only the necessary information required to provide services and comply with legal regulations. Avoid unnecessary data points that could potentially compromise user privacy.</p>
                        <h3>Regular Security Audits</h3>
                        <p>Regular Security Audits: Conduct frequent security audits and penetration testing to identify and rectify any vulnerabilities in your system. Stay updated with the latest security practices and promptly address any weaknesses.</p>
                        <h3>Educate Users</h3>
                        <p>Educate Users: Provide educational resources on privacy best practices, such as how to secure wallets, avoid phishing attacks, and protect personal information. Empowering users with knowledge can significantly enhance their privacy and security.</p>
                        <h3>Strong Encryption and Hashing</h3>
                        <p>Strong Encryption and Hashing: Utilize robust encryption algorithms to secure user communications and transactional data. Additionally, employ cryptographic hashing to protect sensitive information like passwords, ensuring they cannot be reverse-engineered.</p>
                        <h3>User Consent and Control</h3>
                        <p>User Consent and Control: Give users granular control over their privacy settings. Allow them to choose the level of information they wish to disclose and provide options to revoke or modify consent at any time.</p>
					</div>
				</div>
			</div>
		</section>

        <section class="call-action-all">
			<div class="call-action-all-overlay">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<div class="action-text">
								<h2>Get Started Today With Makdfs</h2>
								<p class="lead">Open account for free and start trading Makdfs!</p>
							</div>
							<p class="action-btn"><a class="btn btn-primary" target="_blank" href="https://play.google.com/store/apps/details?id=makdfs.com">Register Now</a></p>
						</div>
					</div>
				</div>
			</div>
        </section>

<?php $this->load->view('components/footer',$data); ?>